name: Close All Pull Requests

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3.0.0
      with:
        comment: "We do not accept PRs. If you have any questions, please feel free to post on Discussions."
